### ISSUE TITLE
Feature request: Consider using EFS instead of S3 for pipeline artifacts

### ISSUE THREAD

**Issue by cabcookie** [moralesl/cdk-pipeline-starter-kit#1]
The standard implementation of the Pipeline Construct uses S3 for pipeline artifacts. However, S3 is a regional service and is pretty slow compared to EFS. See more details here: https://docs.aws.amazon.com/cdk/api/v1/docs/aws-codebuild-readme.html#project-file-system-location-efs
Happy to jointly work on this :-)

**Comment by moralesl** [comment]
Thanks for your input, as the project has been upgraded from the [original API to the modern API](https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/pipelines/ORIGINAL_API.md), the project does not leverage the CodeBuild module directly, and for convenience, maintainability, costs and also accessibility it will stick to S3.
